import os
import re
import time
import json
import logging
from datetime import datetime
from typing import Optional, Dict, Any, List

logger = logging.getLogger(__name__)

class LLMService:
    _instance: Optional['LLMService'] = None

    DEFAULT_SYSTEM_PROMPT = (
        "You are AarogyaMitra, an empathetic, highly knowledgeable AI healthcare assistant for rural India. "
        "Provide accurate medical advice, guidance, and first-aid steps in clear bullet points."
    )

    def __init__(self, model_path: Optional[str] = None):
        if model_path is None:
            backend_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
            model_path = os.path.join(backend_dir, "models", "Qwen3.5-2B.Q4_K_M.gguf")
        
        self.model_path = model_path
        self._model = None

    def _initialize_model(self):
        if self._model is not None:
            return

        if not os.path.exists(self.model_path):
            logger.error(f"Fine-tuned GGUF model not found at path: {self.model_path}")
            raise FileNotFoundError(f"Model file missing at: {self.model_path}")

        try:
            from llama_cpp import Llama
            logger.info(f"Loading fine-tuned model from {self.model_path}...")
            start_time = time.time()
            self._model = Llama(
                model_path=self.model_path,
                n_ctx=2048,
                n_threads=os.cpu_count() or 4,
                verbose=False
            )
            logger.info(f"Model loaded successfully in {time.time() - start_time:.2f}s")
        except Exception as e:
            logger.error(f"Failed to load GGUF model via llama_cpp: {e}")
            raise RuntimeError(f"Model loading error: {e}")

    @classmethod
    def get_instance(cls, model_path: Optional[str] = None) -> 'LLMService':
        if cls._instance is None:
            cls._instance = LLMService(model_path=model_path)
        return cls._instance

    def _clean_response(self, text: str) -> str:
        # Strip <think>...</think> block if generated by Qwen reasoning
        cleaned = re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL).strip()
        # Also strip any trailing or solitary <think> or </think> tags
        cleaned = re.sub(r'</?think>', '', cleaned).strip()
        return cleaned

    def generate_response(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        target_intent: Optional[str] = None,
        max_tokens: int = 512,
        temperature: float = 0.7,
        top_p: float = 0.9,
        repeat_penalty: float = 1.15,
        stop: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        if self._model is None:
            self._initialize_model()

        sys_prompt = system_prompt or self.DEFAULT_SYSTEM_PROMPT
        formatted_prompt = (
            f"<|im_start|>system\n{sys_prompt}<|im_end|>\n"
            f"<|im_start|>user\n{prompt}<|im_end|>\n"
            f"<|im_start|>assistant\n"
        )

        stop_tokens = stop or ["<|im_end|>", "<|endoftext|>"]

        start_time = time.time()
        logger.info(f"Generating response from fine-tuned LLM service... (repeat_penalty={repeat_penalty})")
        
        output = self._model(
            prompt=formatted_prompt,
            max_tokens=max_tokens,
            temperature=temperature,
            top_p=top_p,
            repeat_penalty=repeat_penalty,
            stop=stop_tokens,
            echo=False
        )
        
        elapsed_time = time.time() - start_time
        
        raw_text = ""
        if output and "choices" in output and len(output["choices"]) > 0:
            raw_text = output["choices"][0].get("text", "").strip()

        cleaned_text = self._clean_response(raw_text)
        usage = output.get("usage", {})
        
        result_data = {
            "response": cleaned_text,
            "raw_response": raw_text,
            "execution_time_sec": round(elapsed_time, 3),
            "usage": usage,
            "model_name": os.path.basename(self.model_path),
            "target_intent": target_intent
        }
        
        # Save query and metrics to evaluation log
        try:
            log_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "logs")
            os.makedirs(log_dir, exist_ok=True)
            
            # JSONL File
            jsonl_log_path = os.path.join(log_dir, "llm_evaluations.jsonl")
            log_entry = {
                "timestamp": datetime.utcnow().isoformat() + "Z",
                "prompt": prompt,
                "system_prompt": sys_prompt,
                "target_intent": target_intent,
                "max_tokens": max_tokens,
                "temperature": temperature,
                "top_p": top_p,
                "repeat_penalty": repeat_penalty,
                "model_name": result_data["model_name"],
                "execution_time_sec": result_data["execution_time_sec"],
                "usage": result_data["usage"],
                "response": result_data["response"],
                "raw_response": result_data["raw_response"]
            }
            with open(jsonl_log_path, "a", encoding="utf-8") as f:
                f.write(json.dumps(log_entry) + "\n")
                
            # Markdown File for readability
            md_log_path = os.path.join(log_dir, "llm_evaluations_log.md")
            if not os.path.exists(md_log_path):
                with open(md_log_path, "w", encoding="utf-8") as f:
                    f.write("# LLM Query Evaluation Log\n\n")
            
            with open(md_log_path, "a", encoding="utf-8") as f:
                f.write(f"## Query at {log_entry['timestamp']}\n")
                f.write(f"**Model**: `{log_entry['model_name']}` | **Execution Time**: `{log_entry['execution_time_sec']}s` | **Intent**: `{log_entry['target_intent']}` | **Repeat Penalty**: `{repeat_penalty}`\n")
                f.write(f"**Usage**: `{log_entry['usage']}`\n\n")
                f.write(f"### Prompt:\n```text\n{prompt}\n```\n\n")
                f.write(f"### Response:\n```text\n{result_data['response']}\n```\n\n")
                f.write(f"---\n\n")
                
        except Exception as log_e:
            logger.error(f"Failed to log LLM evaluation query: {log_e}")
        
        return result_data

def get_llm_service() -> LLMService:
    return LLMService.get_instance()
